### ISSUE TITLE
Building for production with Webpack results in errors

### ISSUE THREAD

**Issue by jeffwhitfield** [philipwalton/analyticsjs-boilerplate#7]
I'm currently testing things out and noticed that if I attempt to build for production with Webpack it results in the following errors:

```
ERROR in 0.js from UglifyJs
SyntaxError: Unexpected token: name (Session) [./~/autotrack/lib/session.js:34,0][0.js:43,6]

ERROR in test.js from UglifyJs
SyntaxError: Unexpected token operator «=», expected punc «,» [./~/autotrack/lib/utilities.js:38,
0][test.js:1214,12]
```

I also noticed a few warnings as well:

```
WARNING in ./~/colors/lib/colors.js
138:29-43 Critical dependency: the request of a dependency is an expression

WARNING in ./~/colors/lib/extendStringPrototype.js
101:31-45 Critical dependency: the request of a dependency is an expression
```

Not sure what the answer is. Not much of a Webpack expert to be honest. :P

**Comment by philipwalton** [comment]
I've update the repo to remove the `node_modules` exclusion from the babel loader. I think that should fix the first errors.

I'm not sure what the second set of errors are from. Are you sure that's webpack and not just npm install warnings?

**Comment by jeffwhitfield** [comment]
Alright, so here's what I'm getting when I run either `webpack` or `webpack -p`:

```
(node:72465) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
[BABEL] Note: The code generator has deoptimised the styling of "/Users/jeffwhitfield/Sites/analytics/node_modules/text-encoding/lib/encoding-indexes.js" as it exceeds the max of "500KB".
  [24] (webpack)/buildin/global.js 808 bytes {1} [built]
  [76] ./~/sinon/lib/sinon.js 3.2 kB {1} [built]
 [114] ./~/querystring-es3/index.js 126 bytes {1} [built]
 [122] ./src/analytics/base.js 7.78 kB {0} {1} [built]
 [171] ./~/babel-polyfill/lib/index.js 833 bytes {1} [built]
 [172] ./test/analytics/autotrack-test.js 6.5 kB {1} [built]
 [173] ./test/analytics/base-test.js 5.39 kB {1} [built]
 [174] ./test/analytics/multiple-trackers-test.js 8.58 kB {1} [built]
 [186] ./~/core-js/fn/regexp/escape.js 107 bytes {1} [built]
 [366] ./~/core-js/shim.js 7.38 kB {1} [built]
 [377] ./~/regenerator-runtime/runtime.js 24.1 kB {1} [built]
 [393] ./src/analytics/autotrack.js 9.53 kB {1} [built]
 [394] ./src/analytics/multiple-trackers.js 12.5 kB {1} [built]
 [395] ./src/index.js 468 bytes {2} [built]
 [396] multi babel-polyfill ./test/analytics/autotrack-test.js ./test/analytics/base-test.js ./test/analytics/multiple-trackers-test.js 64 bytes {1} [built]
    + 382 hidden modules

WARNING in ./~/colors/lib/colors.js
139:29-43 Critical dependency: the request of a dependency is an expression

WARNING in ./~/colors/lib/extendStringPrototype.js
95:31-45 Critical dependency: the request of a dependency is an expression

ERROR in ./~/sinon/~/diff/lib/index.js
Module build failed: Error: Couldn't find preset "es3" relative to directory "/Users/jeffwhitfield/Sites/analytics/node_modules/sinon/node_modules/diff"
    at /Users/jeffwhitfield/Sites/analytics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/jeffwhitfield/Sites/analytics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/jeffwhitfield/Sites/analytics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/jeffwhitfield/Sites/analytics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/jeffwhitfield/Sites/analytics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/jeffwhitfield/Sites/analytics/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/jeffwhitfield/Sites/analytics/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/jeffwhitfield/Sites/analytics/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/jeffwhitfield/Sites/analytics/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/jeffwhitfield/Sites/analytics/node_modules/babel-loader/lib/index.js:134:16)
 @ ./~/sinon/lib/sinon/spy.js 26:13-28
 @ ./~/sinon/lib/sinon.js
 @ ./test/analytics/autotrack-test.js
 @ multi babel-polyfill ./test/analytics/autotrack-test.js ./test/analytics/base-test.js ./test/analytics/multiple-trackers-test.js
```

For testing, I created a new copy of the Analytics.js Boilerplate repo and did a fresh install of the NPM modules. Hrm. :P

**Comment by jeffwhitfield** [comment]
Looks like it's just the test entries that are causing the issues now. If I nix them from the config then it compiles the index fine.

**Comment by philipwalton** [comment]
> Looks like it's just the test entries that are causing the issues now. If I nix them from the config then it compiles the index fine.

Yeah, you can definitely exclude the tests for your setup.

I've also [updated the loader options](https://github.com/philipwalton/analyticsjs-boilerplate/commit/74406ca69b26c5699a5046a52025650f048069c7) to whitelist autotrack dependencies, so I think it should work for you now. Let me know if it doesn't.

**Comment by jeffwhitfield** [comment]
That did the trick.  :D

**Comment by asuh** [comment]
I'm having the same errors above, even with the updated loader options. I did as @jeffwhitfield said and deleted line 7, which contains the test.js file, from the config file and it compiled successfully.

**Comment by philipwalton** [comment]
@asuh can you show me your webpack config?

**Comment by asuh** [comment]
Here's what worked for me:
https://gist.github.com/asuh/f9f49dba47c3a949f2733882c397958d

**Comment by philipwalton** [comment]
Can you show what config you had that didn't work when using the `test` entry?

**Comment by asuh** [comment]
The config that didn't work for me was a clone of this repo as is. I didn't change anything from the original clone. I successfully ran `npm install` and then it gave me the errors above when I ran `npm start`

**Comment by philipwalton** [comment]
Hmm, this might be related to your npm setup described in #8. I've just tried a fresh clone and `npm install` and running `npm start` worked for me.

What version of node are you on? And what OS?

**Comment by asuh** [comment]
Strange, that might be possible.

Node 7.5
Windows 10 Home

**Comment by philipwalton** [comment]
I don't have a windows machine to test on, but I tried on my Mac using Node 7.5 and a fresh clone/npm install, and it worked.

**Comment by asuh** [comment]
I also just tried this on my macOS 10.12.3 and it worked fine. 

I then used Virtualbox machine with Windows 7, installed Node 7.6, and ran the files. The same errors were displayed. I once again removed line 7 with the test script and it compiled successfully.

Looks like there's something in here that's not working on Windows installations.

**Comment by asuh** [comment]
I believe the issue is the double asterisk on line 7.

I changed it to this:

`'test': ['babel-polyfill', ...glob.sync('./test/*-test.js')],`

ran `npm start` and it compiled successfully.

I believe Windows can trip up on `/**/` in paths but I don't remember why or how to fix it.
